blog/blog/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include('main.urls')),

]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')),)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from . import views


app_name = 'main'
urlpatterns = [
    path('', views.PostIndex.as_view(), name='index'),
    path('create_post', views.CreatePost.as_view(), name='create_post'),
    path('show_post/<slug:post_slug>', views.ShowPost.as_view(), name='show_post'),
    path('show_category/<slug:category_slug>', views.ShowCategory.as_view(), name='show_category'),
    path('login', views.LoginUser.as_view(), name='login'),
    path('logout', views.LogoutUser.as_view(), name='logout'),
    path('register', views.RegisterUser.as_view(), name='register'),
    path('my_account', views.MyAccount.as_view(), name='my_account'),
    # path('password', auth_views.PasswordChangeView.as_view(template_name='main/change-password.html'))
    path('password/', views.PasswordsChangeView.as_view(template_name='main/change_password.html')),
    path('password_success', views.password_success, name='password_success'),
]

blog/main/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from unidecode import unidecode
from django.shortcuts import reverse
from django.db import models
from django.utils.text import slugify
from django.contrib.auth.models import PermissionsMixin


class Category(models.Model):
    name = models.CharField('Имя', max_length=20, unique=True, db_index=True)
    slug = models.SlugField('URL', max_length=20, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        unique_together = [['name', 'slug']]

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField('Название', max_length=500)
    slug = models.SlugField('URL статьи', max_length=500, unique=True, db_index=True)
    text = models.TextField('Текст')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='Категория')
    image = models.ImageField('Картинка', upload_to='main')
    publish_date = models.DateTimeField('Время публикации', max_length=500, auto_now_add=True)

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'
        get_latest_by = 'publish_date'

    def get_absolute_url(self):
        return reverse('main:show_post', kwargs={'post_slug': self.slug})

    def save(self, *args, **kwargs):
        last_obj = Post.objects.all().order_by('id').last()
        if last_obj:
            last_pk = last_obj.pk + 1
        else:
            last_pk = 1
        string = unidecode(str(self.title) + str(last_pk))
        self.slug = slugify(string)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.title


class MyUserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('Почтовый адрес должен быть задан!')
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_user(self, email, password, **extra_fields):
        extra_fields['is_staff'] = False
        extra_fields['is_superuser'] = False
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields['is_staff'] = True
        extra_fields['is_superuser'] = True
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField('Почтовый адрес', max_length=50, db_index=True, unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)
    bio = models.CharField('bio', max_length=100, blank=True)
    avatar = models.FileField(upload_to='avatars/', null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = MyUserManager()

    @classmethod
    def get_username_by_id(cls, id):
        user = cls.objects.get(pk=id)
        username = user.email.split('@')[0]
        return username

    class Meta:
        verbose_name = 'user'
        verbose_name_plural = 'users'

blog/main/views.py
import logging
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.shortcuts import reverse, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView

from .models import Post, Category
from .form import PostForm, LoginUserForm, RegisterUserForm, PasswordChangingForm

logger = logging.getLogger('main')


class PostIndex(ListView):
    model = Post
    template_name = 'main/index.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        extra_user = {
            'username': self.request.user,
            'userip': self.request.META['REMOTE_ADDR'],
            'path': self.request.path,
        }
        logger.info('Getting posts from db', extra=extra_user)
        return PostIndex.model.objects.all().order_by('-publish_date', 'title').select_related('category')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['title'] = 'Главная'
        context['categories'] = Category.objects.all()

        return context


class CreatePost(LoginRequiredMixin, CreateView):
    form_class = PostForm
    login_url = reverse_lazy('main:login')
    template_name = 'main/create_post.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Создать новый пост'
        return context


class ShowPost(DetailView):
    model = Post
    template_name = 'main/show_post.html'
    slug_url_kwarg = 'post_slug'


class ShowCategory(ListView):
    model = Post
    template_name = 'main/index.html'
    context_object_name = 'posts'
    paginate_by = 10
    allow_empty = True

    def get_queryset(self):
        return ShowCategory.model.objects.filter(category__slug=self.kwargs['category_slug'])

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        cat = Category.objects.get(slug=self.kwargs['category_slug'])
        context['title'] = f'Категория: {cat.name}'
        context['categories'] = Category.objects.all()
        context['selected_cat'] = cat.name
        return context


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'main/login.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизация'
        return context

    def get_success_url(self):
        return reverse('main:index')


class LogoutUser(LogoutView):
    next_page = reverse_lazy('main:index')


class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('main:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Регистрация'
        return context


class PasswordsChangeView(PasswordChangeView):
    form_class = PasswordChangingForm
    success_url = reverse_lazy('password_success')


def password_success(request):
    return render(request, 'main/password_success.html', {})


class MyAccount(LoginView):
    form_class = LoginUserForm
    template_name = 'main/my_account.html'

blog/main/templates/main/base.html
{% load static %}
{% load cache %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <style> a:after { color: #ffc107} </style>
</head>
<body>

<header>

    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <div class="d-flex justify-content-start">
                <a href="{% url 'main:index' %}" class="navbar-brand d-flex align-items-center">
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                         class="bi bi-bricks"
                         viewBox="0 0 16 16">
                        <path d="M0 .5A.5.5 0 0 1 .5 0h15a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5H14v2h1.5a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5H14v2h1.5a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5H.5a.5.5 0 0 1-.5-.5v-3a.5.5 0 0 1 .5-.5H2v-2H.5a.5.5 0 0 1-.5-.5v-3A.5.5 0 0 1 .5 6H2V4H.5a.5.5 0 0 1-.5-.5v-3zM3 4v2h4.5V4H3zm5.5 0v2H13V4H8.5zM3 10v2h4.5v-2H3zm5.5 0v2H13v-2H8.5zM1 1v2h3.5V1H1zm4.5 0v2h5V1h-5zm6 0v2H15V1h-3.5zM1 7v2h3.5V7H1zm4.5 0v2h5V7h-5zm6 0v2H15V7h-3.5zM1 13v2h3.5v-2H1zm4.5 0v2h5v-2h-5zm6 0v2H15v-2h-3.5z"/>
                    </svg>
                    <strong> Ermilion</strong>
                </a>
            </div>
            <div class="d-flex justify-content-end">
                {% if request.user.is_authenticated %}

                <strong class="navbar-brand">{{ user.email }}</strong>
                <strong class="navbar-brand"> | </strong>
                <a href="{% url 'main:logout' %}" class="btn btn-warning"><strong>Выйти</strong></a>
                <strong class="navbar-brand"> </strong>
                <div class="dropdown text-end">
                    <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser1"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        {% if user.avatar %}
                        <img src="{{ user.avatar.url }}" alt="mdo" width="32" height="32" class="rounded-circle">
                        {% else %}
                        <img
                                src="https://vk.com/images/camera_200.png" alt="" width="40" height="40"
                                class="rounded-circle">
                        {% endif %}
                    </a>
                    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
                        {% if request.user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'main:create_post' %}">Добавить новость</a></li>
                        {% endif %}
                        <li><a class="dropdown-item" href="#">Возможные настройки</a></li>
                        <li><a class="dropdown-item" href="{% url 'main:my_account' %}">Личный кабинет</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="password">Настройки</a></li>
                    </ul>
                </div>
                {% else %}
                <a href="{% url 'main:register' %}" class="btn btn-warning"><strong>Регистрация</strong></a>
                <strong class="navbar-brand"> </strong>
                <a href="{% url 'main:login' %}" class="btn btn-outline-light me-2"><strong>Войти</strong></a>
                {% endif %}

            </div>
        </div>
    </div>
</header>


<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            {% block section %}{% endblock section %}
        </div>
        </div>
    </section>
    {% block content %}{% endblock content %}
</main>

<footer class="text-muted py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">Данное приложение явлется учебным проектом.</p>
        <p class="mb-0">Все новости взяты с <a href="https://tengrinews.kz">ЭТОГО САЙТА</a>.</p>
    </div>
</footer>
</body>
</html>

blog/main/templates/main/change_password.html
dc{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Смена пароля...</h1>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="w-100 d-flex flex-column justify-content-center align-items-center">
            {% csrf_token %}
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
                <div class="form-floating mb-3 w-25">
                    {{ widget }}
                    {{ widget.label_tag }}
                </div>
                {% if widget.errors %}
                    <ol>
                    {% for error in widget.errors %}
                        <li><strong class="text-danger">{{ error }}</strong></li>
                    {% endfor %}
                    </ol>
                {% endif %}
            {% endfor %}
            <button class="btn btn-lg btn-primary" type="submit">Изменить пароль</button>
        </form>
    </div>
</div>
{% endblock content %}

blog/main/templates/main/create_post.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Создание поста</h1>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex flex-column align-items-center justify-content-center">
        <form class="needs-validation w-100 d-flex flex-column align-items-center" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            <div class="row g-3 d-flex flex-column align-items-center w-50">
            {% for widget in form %}
                {% if widget.label != 'Картинка' %}
                <div class="col-12">
                {% else %}
                <div class="col-8">
                {% endif %}
                    {{ widget.label_tag }}
                    {{ widget }}
                </div>
                {% if widget.errors %}
                    <ol>
                        {% for error in widget.errors %}
                        <li><strong class="text-danger">{{ error }}</strong></li>
                        {% endfor %}
                    </ol>
                {% endif %}
            {% endfor %}
            </div>
            <hr class="my-4">
            <button class="w-25 btn btn-primary btn-lg" type="submit">Опубликовать</button>
        </form>
        {% if error %}
        <p class="text-danger">{{ error }}</p>
        {% endif %}
    </div>
</div>
{% endblock content %}

blog/main/templates/main/edit_user.html
{% extends 'main/base.html' %}

{% block title %}{{ user.username }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Смена личных данных</h1>

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="form-group">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
        </form>
    </div>
</div>

{% endblock section %}
{% block content %}


{% endblock content %}

blog/main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Доступные посты</h1>


<div class="dropdown text-end">
    <a href="#" class="d-flex align-items-center col-lg-4 mb-2 mb-lg-0 link-dark text-decoration-none dropdown-toggle"
       id="dropdownUser1"
       data-bs-toggle="dropdown" aria-expanded="false">
        <h1 class="fw-light">Выберете категорию</h1>
    </a>
    <ul class="dropdown-menu text-small" aria-labelledby="dropdownUser1" style="">
        {% for cat in categories %}
        {% if cat.name == selected_cat %}
        <li><span class="dropdown-item active"> {{ cat.name }} </span></li>
        {% else %}
        <li><a href="{% url 'main:show_category' cat.slug %}" class="dropdown-item"> {{ cat.name }} </a>
        </li>
        {% endif %}

        {% empty %}
        <p class="text-muted">Пока нет ни одной категории</p>
        {% endfor %}
    </ul>
</div>


{% endblock section %}


{% block content %}


<div class="album py-5 bg-light">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-1 g-2">
            {% for post in posts %}
            <a href="{% url 'main:show_post' post.slug %}" style="text-decoration: none; color: #666">
                <div class="card mb-3 card h-100">
                    <div class="row g-0">
                        <div class="col-md-4 scaler">
                            <img src="{{ post.image.url }}" class="img-fluid rounded-start" alt="...">
                        </div>
                        <div class="col-md-8">
                            <div class="card-body">
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.text|truncatechars:200 }}</p>
                                </p>
                                <small class="text-muted">Дата публикации: {{ post.publish_date }}</small>
                            </div>
                        </div>

                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <small class="text-muted">"{{ post.category.name }}"                  </small>

                        <small><a href="{% url 'main:show_post' post.slug %}" class="link-warning"
                                  style="text-shadow: black 0 0 1px">Читать
                            -></a></small>
                    </div>
                </div>

            </a>



            {% empty %}
            <h1>Мы работаем над заполнением ленты новостей</h1>
            {% endfor %}
        </div>
        {% if page_obj.has_other_pages %}
        <nav class="mt-5" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="btn btn-outline-secondary" href="?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Назад</a>
                </li>
                {% endif %}
                {% for page in paginator.page_range %}
                {% if page_obj.number == page %}
                <li class="page-item active "><a class="btn btn-warning" style="text-shadow: black 0px 0px 10px"
                                                 href="?page={{ page }}">{{ page }}</a></li>
                {% elif page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                <li class="page-item"><a class="btn btn-outline-secondary" href="?page={{ page }}">{{ page }}</a></li>
                {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="btn btn-outline-secondary" href="?page={{ page_obj.next_page_number }}">Далее</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Далее</a>
                </li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    </div>
</div>
{% endblock content %}

blog/main/templates/main/login.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Вход на сайт</h1>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="w-100 d-flex flex-column justify-content-center align-items-center">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Введите данные пользователя для входа</h1>
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
                <div class="form-floating mb-3 w-25">
                    {{ widget }}
                    {{ widget.label_tag }}
                </div>
                {% if widget.errors %}
                    <ol>
                    {% for error in widget.errors %}
                        <li><strong class="text-danger">{{ error }}</strong></li>
                    {% endfor %}
                    </ol>
                {% endif %}
            {% endfor %}
            <button class="btn btn-lg btn-primary" type="submit">Войти</button>
        </form>
    </div>
</div>
{% endblock content %}

blog/main/templates/main/my_account.html
{% extends 'main/base.html' %}

{% block title %}{{ user.username }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Личный кабинет</h1>
{% if request.user.is_authenticated %}
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class=" image d-flex flex-column justify-content-center align-items-center">

            {% if user.avatar %}
            <img src="{{ user.avatar.url }}">
            {% else %}
            <img src="https://vk.com/images/camera_200.png" alt="">
            {% endif %}
            <span class="name mt-3">{{ user.email }}</span>
            <span class="name mt-3">{{ user.bio }}</span>

            <span><i class="fa fa-copy"></i></span>
        </div>
        <div class="d-flex flex-row justify-content-center align-items-center mt-3">
            <a href="password">Вы можете изменить свой пароль</a>
        </div>
    </div>
</div>
{% else %}
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <h1>У вас нет доступа к личному кабинету.</h1>
        <h3>Пройдите процедуру регистрации или авторизации</h3>
    </div>
</div>
{% endif %}

{% endblock section %}
{% block content %}


{% endblock content %}

blog/main/templates/main/password_success.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<h1 class="fw-light">{{ post.title }}</h1>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light d-flex flex-column justify-content-center align-items-center">
    <h1>Пароль успешно изменён</h1>
</div>
{% endblock content %}

blog/main/templates/main/register.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}
<h1 class="fw-light">Регистрация</h1>
{% endblock section %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container d-flex justify-content-center">
        <form method="post" class="w-100 d-flex flex-column justify-content-center align-items-center"
              enctype="multipart/form-data">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal text-center">Введите данные нового пользователя</h1>
            <strong class="text-danger">{{ form.non_field_errors }}</strong>
            {% for widget in form %}
            <div class="form-floating mb-3 w-25">
                {{ widget }}
                {{ widget.label_tag }}
            </div>
            {% if widget.errors %}
            <ol>
                {% for error in widget.errors %}
                <li><strong class="text-danger">{{ error }}</strong></li>
                {% endfor %}
            </ol>
            {% endif %}
            {% endfor %}
            <button class="btn btn-lg btn-primary" type="submit">Зарегистрироваться</button>
        </form>
    </div>
</div>
{% endblock content %}

blog/main/templates/main/show_post.html
{% extends 'main/base.html' %}

{% block title %}{{ title }}{% endblock title %}

{% block section %}

<div class="album py-5 bg-light d-flex flex-column justify-content-center align-items-center">
    <h1 class="fw-light">{{ post.title }}</h1>
    <img src="{{ post.image.url }}" alt="">
    <p>{{ post.text }}</p>
</div>
{% endblock section %}